version: '3'

services:
  api:
    image: api_local
    restart: always
    ports:
      - "5000:5000"

  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
#      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    volumes:
    - ./data:/var/lib/postgresql/data

